[tool.poetry]
name = "matrix-factorization-py"
version = "0.1.0"
description = ""
authors = ["devbruce <bruce93k@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
numpy = "~2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
